In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
liver = pd.read_csv("cirrhosis.csv")
liver.head(10)

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261.0,2.60,156.0,1718.0,137.95,172.0,190.0,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302.0,4.14,54.0,7394.8,113.52,88.0,221.0,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176.0,3.48,210.0,516.0,96.10,55.0,151.0,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244.0,2.54,64.0,6121.8,60.63,92.0,183.0,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279.0,3.53,143.0,671.0,113.15,72.0,136.0,10.9,3.0
5,6,2503,D,Placebo,24201,F,N,Y,N,N,0.8,248.0,3.98,50.0,944.0,93.00,63.0,NaN,11.0,3.0
6,7,1832,C,Placebo,20284,F,N,Y,N,N,1.0,322.0,4.09,52.0,824.0,60.45,213.0,204.0,9.7,3.0
7,8,2466,D,Placebo,19379,F,N,N,N,N,0.3,280.0,4.00,52.0,4651.2,28.38,189.0,373.0,11.0,3.0
8,9,2400,D,D-penicillamine,15526,F,N,N,Y,N,3.2,562.0,3.08,79.0,2276.0,144.15,88.0,251.0,11.0,2.0
9,10,51,D,Placebo,25772,F,Y,N,Y,Y,12.6,200.0,2.74,140.0,918.0,147.25,143.0,302.0,11.5,4.0

In [3]:
liver.isna().any()

ID               False
N_Days           False
Status           False
Drug              True
Age              False
Sex              False
Ascites           True
Hepatomegaly      True
Spiders           True
Edema            False
Bilirubin        False
Cholesterol       True
Albumin          False
Copper            True
Alk_Phos          True
SGOT              True
Tryglicerides     True
Platelets         True
Prothrombin       True
Stage             True
dtype: bool

In [4]:
liver.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             418 non-null    int64
 1   N_Days         418 non-null    int64
 2   Status         418 non-null    object
 3   Drug           312 non-null    object
 4   Age            418 non-null    int64
 5   Sex            418 non-null    object
 6   Ascites        312 non-null    object
 7   Hepatomegaly   312 non-null    object
 8   Spiders        312 non-null    object
 9   Edema          418 non-null    object
 10  Bilirubin      418 non-null    float64
 11  Cholesterol    284 non-null    float64
 12  Albumin        418 non-null    float64
 13  Copper         310 non-null    float64
 14  Alk_Phos       312 non-null    float64
 15  SGOT           312 non-null    float64
 16  Tryglicerides  282 non-null    float64
 17  Platelets      407 non-null    float64
 18  Prothrombin    416 non-null    float64
 19  Stage          412 non-null    float64
dtypes: float64(10), int64(3), object(7)
memory usage: 65.4+ KB

In [5]:
len(liver['Drug'].value_counts())

2

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median',missing_values=np.nan)
for i in liver.columns:
    if liver[i].dtype=='int64' or liver[i].dtype=='float64':
        imputer=imputer.fit(liver[[i]])
        liver[i]=imputer.transform(liver[[i]])

In [7]:
liver.isna().any()

ID               False
N_Days           False
Status           False
Drug              True
Age              False
Sex              False
Ascites           True
Hepatomegaly      True
Spiders           True
Edema            False
Bilirubin        False
Cholesterol      False
Albumin          False
Copper           False
Alk_Phos         False
SGOT             False
Tryglicerides    False
Platelets        False
Prothrombin      False
Stage            False
dtype: bool

In [8]:
for i in liver.columns:
    if liver[i].dtype=='object':
        liver[i]=liver.fillna(liver[i].value_counts().index[0])

In [9]:
for i in liver.columns:
    if liver[i].dtype=='object':
        if len(liver[i].value_counts()) == 2:
            liver[i]=liver.replace({i:{liver[i].value_counts().index[0]:0 , liver[i].value_counts().index[1]:1}})
        else:
            liver[i]=liver.replace({i:{liver[i].value_counts().index[0]:0 , liver[i].value_counts().index[1]:1,liver[i].value_counts().index[2]:2}})

In [10]:
liver.head()

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1.0,400.0,1,1,21464.0,1,1,1,1,1,14.5,261.0,2.60,156.0,1718.0,137.95,172.0,190.0,12.2,4.0
1,2.0,4500.0,2,2,20617.0,2,2,2,2,2,1.1,302.0,4.14,54.0,7394.8,113.52,88.0,221.0,10.6,3.0
2,3.0,1012.0,3,3,25594.0,3,3,3,3,3,1.4,176.0,3.48,210.0,516.0,96.10,55.0,151.0,12.0,4.0
3,4.0,1925.0,4,4,19994.0,4,4,4,4,4,1.8,244.0,2.54,64.0,6121.8,60.63,92.0,183.0,10.3,4.0
4,5.0,1504.0,5,5,13918.0,5,5,5,5,5,3.4,279.0,3.53,143.0,671.0,113.15,72.0,136.0,10.9,3.0

In [11]:
liver.isna().any()

ID               False
N_Days           False
Status           False
Drug             False
Age              False
Sex              False
Ascites          False
Hepatomegaly     False
Spiders          False
Edema            False
Bilirubin        False
Cholesterol      False
Albumin          False
Copper           False
Alk_Phos         False
SGOT             False
Tryglicerides    False
Platelets        False
Prothrombin      False
Stage            False
dtype: bool

In [12]:
liver.info()
liver=liver.astype({'Stage':int})
liver.head(30)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             418 non-null    float64
 1   N_Days         418 non-null    float64
 2   Status         418 non-null    object
 3   Drug           418 non-null    object
 4   Age            418 non-null    float64
 5   Sex            418 non-null    object
 6   Ascites        418 non-null    object
 7   Hepatomegaly   418 non-null    object
 8   Spiders        418 non-null    object
 9   Edema          418 non-null    object
 10  Bilirubin      418 non-null    float64
 11  Cholesterol    418 non-null    float64
 12  Albumin        418 non-null    float64
 13  Copper         418 non-null    float64
 14  Alk_Phos       418 non-null    float64
 15  SGOT           418 non-null    float64
 16  Tryglicerides  418 non-null    float64
 17  Platelets      418 non-null    float64
 18  Prothrombin    418 non-null    float64
 19  Stage          418 non-null    float64
dtypes: float64(13), object(7)
memory usage: 65.4+ KB

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1.0,400.0,1,1,21464.0,1,1,1,1,1,14.5,261.0,2.60,156.0,1718.0,137.95,172.0,190.0,12.2,4
1,2.0,4500.0,2,2,20617.0,2,2,2,2,2,1.1,302.0,4.14,54.0,7394.8,113.52,88.0,221.0,10.6,3
2,3.0,1012.0,3,3,25594.0,3,3,3,3,3,1.4,176.0,3.48,210.0,516.0,96.10,55.0,151.0,12.0,4
3,4.0,1925.0,4,4,19994.0,4,4,4,4,4,1.8,244.0,2.54,64.0,6121.8,60.63,92.0,183.0,10.3,4
4,5.0,1504.0,5,5,13918.0,5,5,5,5,5,3.4,279.0,3.53,143.0,671.0,113.15,72.0,136.0,10.9,3
5,6.0,2503.0,6,6,24201.0,6,6,6,6,6,0.8,248.0,3.98,50.0,944.0,93.00,63.0,251.0,11.0,3
6,7.0,1832.0,7,7,20284.0,7,7,7,7,7,1.0,322.0,4.09,52.0,824.0,60.45,213.0,204.0,9.7,3
7,8.0,2466.0,8,8,19379.0,8,8,8,8,8,0.3,280.0,4.00,52.0,4651.2,28.38,189.0,373.0,11.0,3
8,9.0,2400.0,9,9,15526.0,9,9,9,9,9,3.2,562.0,3.08,79.0,2276.0,144.15,88.0,251.0,11.0,2
9,10.0,51.0,10,10,25772.0,10,10,10,10,10,12.6,200.0,2.74,140.0,918.0,147.25,143.0,302.0,11.5,4
10,11.0,3762.0,11,11,19619.0,11,11,11,11,11,1.4,259.0,4.16,46.0,1104.0,79.05,79.0,258.0,12.0,4
11,12.0,304.0,12,12,21600.0,12,12,12,12,12,3.6,236.0,3.52,94.0,591.0,82.15,95.0,71.0,13.6,4
12,13.0,3577.0,13,13,16688.0,13,13,13,13,13,0.7,281.0,3.85,40.0,1181.0,88.35,130.0,244.0,10.6,3
13,14.0,1217.0,14,14,20535.0,14,14,14,14,14,0.8,309.5,2.27,43.0,728.0,71.00,108.0,156.0,11.0,4
14,15.0,3584.0,15,15,23612.0,15,15,15,15,15,0.8,231.0,3.87,173.0,9009.8,127.71,96.0,295.0,11.0,3
15,16.0,3672.0,16,16,14772.0,16,16,16,16,16,0.7,204.0,3.66,28.0,685.0,72.85,58.0,198.0,10.8,3
16,17.0,769.0,17,17,19060.0,17,17,17,17,17,2.7,274.0,3.15,159.0,1533.0,117.80,128.0,224.0,10.5,4
17,18.0,131.0,18,18,19698.0,18,18,18,18,18,11.4,178.0,2.80,588.0,961.0,280.55,200.0,283.0,12.4,4
18,19.0,4232.0,19,19,18102.0,19,19,19,19,19,0.7,235.0,3.56,39.0,1881.0,93.00,123.0,209.0,11.0,3
19,20.0,1356.0,20,20,21898.0,20,20,20,20,20,5.1,374.0,3.51,140.0,1919.0,122.45,135.0,322.0,13.0,4
20,21.0,3445.0,21,21,23445.0,21,21,21,21,21,0.6,252.0,3.83,41.0,843.0,65.10,83.0,336.0,11.4,4
21,22.0,673.0,22,22,20555.0,22,22,22,22,22,3.4,271.0,3.63,464.0,1376.0,120.90,55.0,173.0,11.6,4
22,23.0,264.0,23,23,20442.0,23,23,23,23,23,17.4,395.0,2.94,558.0,6064.8,227.04,191.0,214.0,11.7,4
23,24.0,4079.0,24,24,16261.0,24,24,24,24,24,2.1,456.0,4.00,124.0,5719.0,221.88,230.0,70.0,9.9,2
24,25.0,4127.0,25,25,16463.0,25,25,25,25,25,0.7,298.0,4.10,40.0,661.0,106.95,66.0,324.0,11.3,2
25,26.0,1444.0,26,26,19002.0,26,26,26,26,26,5.2,1128.0,3.68,53.0,3228.0,165.85,166.0,421.0,9.9,3
26,27.0,77.0,27,27,19884.0,27,27,27,27,27,21.6,175.0,3.31,221.0,3697.4,101.91,168.0,80.0,12.0,4
27,28.0,549.0,28,28,16417.0,28,28,28,28,28,17.2,222.0,3.23,209.0,1975.0,189.10,195.0,144.0,13.0,4
28,29.0,4509.0,29,29,23331.0,29,29,29,29,29,0.7,370.0,3.78,24.0,5833.0,73.53,86.0,390.0,10.6,2
29,30.0,321.0,30,30,15116.0,30,30,30,30,30,3.6,260.0,2.54,172.0,7277.0,121.26,158.0,124.0,11.0,4

In [13]:
from sklearn.model_selection import train_test_split
liver.drop(['ID'],axis=1)
X=liver.drop(['Stage'],axis=1)
y=liver['Stage']
X=X.values
y=y.values
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=25)

In [24]:
#from sklearn.tree import DecisionTreeRegressor
#dreg = DecisionTreeRegressor()

from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()

#from sklearn.neighbors import KNeighborsClassifier
#knn = KNeighborsClassifier(n_neighbors=5)
#knn.fit(X_train,y_train)

In [30]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
reX_train=scaler.fit_transform(X_train)
reX_test=scaler.transform(X_test)

In [31]:
logreg.fit(reX_train,y_train)

LogisticRegression()

In [33]:
y_pred= logreg.predict(reX_test)
print(y_test,y_pred)

[2 4 1 4 3 2 2 3 4 2 4 3 2 4 4 3 4 3 3 2 4 3 2 4 3 2 4 2 3 3 4 3 4 2 4 4 3
 4 3 2 4 2 4 2 3 4 4 3 3 3 4 3 3 3 3 3 4 3 4 3 3 2 3 3 4 2 4 1 4 1 4 4 3 3
 3 1 4 2 2 2 4 4 4 4 1 4 3 2 4 4 4 4 3 3 3 4 3 3 3 4 3 4 2 4 4 4 3 2 3 3 3
 4 3 2 3 3 1 4 3 4 3 3 3 3 3 4] [3 3 3 4 3 4 3 4 4 2 4 3 4 3 4 4 3 3 3 2 4 4 4 4 4 3 3 3 3 4 4 4 4 3 3 3 2
 4 3 3 4 2 3 4 3 3 4 3 3 3 4 3 3 4 4 3 3 4 4 4 3 4 2 3 3 3 4 2 4 3 3 4 3 4
 3 3 4 3 3 3 4 3 4 4 3 4 3 3 3 4 3 4 3 4 3 4 3 3 3 4 4 3 3 3 4 3 4 2 3 3 4
 4 3 2 3 3 3 3 3 4 3 3 3 3 3 4]

In [34]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.5396825396825397
[[ 0  1  5  0]
 [ 0  5 12  5]
 [ 0  2 34 15]
 [ 0  0 18 29]]